/* Generated by CMake */

#cmakedefine BSD 1
#cmakedefine C_ATTRIBUTE_ALWAYS_INLINE 1
#cmakedefine C_ATTRIBUTE_FASTCALL 1
#cmakedefine C_CORE_INLINE 1
#cmakedefine C_DEBUG 1
#cmakedefine C_DIRECTSERIAL 1
#cmakedefine C_DYNAMIC_X86 1
#cmakedefine C_DYNREC 1
#cmakedefine C_FPU 1
#cmakedefine C_FPU_X86 1
#cmakedefine C_HAS_ATTRIBUTE 1
#cmakedefine C_HAS_BUILTIN_EXPECT 1
#cmakedefine C_HAVE_MPROTECT 1
#cmakedefine C_HEAVY_DEBUG 1
#cmakedefine C_IPX 1
#cmakedefine C_MODEM 1
#cmakedefine C_OPENGL 1
#cmakedefine C_SDL_SOUND 1
#cmakedefine C_SET_PRIORITY 1
#cmakedefine C_SSHOT 1
#cmakedefine C_UNALIGNED_MEMORY 1
#cmakedefine C_X11_XKB 1
#define C_TARGETCPU @C_TARGETCPU@
#cmakedefine DB_HAVE_NO_POWF 1
#cmakedefine DIRENT_HAS_D_TYPE 1
#cmakedefine ENVIRON_INCLUDED 1
#cmakedefine ENVIRON_LINKED 1
#cmakedefine HAVE_ALSA 1
#cmakedefine HAVE_DDRAW_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_MEMORY_H 1
#cmakedefine HAVE_NETINET_IN_H 1
#cmakedefine HAVE_PWD_H 1
#cmakedefine HAVE_REALPATH 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine LINUX 1
#cmakedefine MACOSX 1
#cmakedefine OS2 1

#define PACKAGE "@PACKAGE@"
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"
#define PACKAGE_NAME "@PACKAGE_NAME@"
#define PACKAGE_STRING "@PACKAGE_STRING@"
#define PACKAGE_TARNAME "@PACKAGE_TARNAME@"
#define PACKAGE_URL "@PACKAGE_URL@"
#define PACKAGE_VERSION "@PACKAGE_VERSION@"

#define SIZEOF_INT_P @SIZEOF_INT_P@
#define SIZEOF_UNSIGNED_CHAR @SIZEOF_UNSIGNED_CHAR@
#define SIZEOF_UNSIGNED_INT @SIZEOF_UNSIGNED_INT@
#define SIZEOF_UNSIGNED_LONG @SIZEOF_UNSIGNED_LONG@
#define SIZEOF_UNSIGNED_LONG_LONG @SIZEOF_UNSIGNED_LONG_LONG@
#define SIZEOF_UNSIGNED_SHORT @SIZEOF_UNSIGNED_SHORT@

#define STDC_HEADERS @STDC_HEADERS@
#define VERSION "@VERSION@"

#cmakedefine WORDS_BIGENDIAN 1

#if C_ATTRIBUTE_ALWAYS_INLINE
#define INLINE inline __attribute__((always_inline))
#else
#define INLINE inline
#endif

#if C_ATTRIBUTE_FASTCALL
#define DB_FASTCALL __attribute__((fastcall))
#else
#define DB_FASTCALL
#endif

#if C_HAS_ATTRIBUTE
#define GCC_ATTRIBUTE(x) __attribute__ ((x))
#else
#define GCC_ATTRIBUTE(x)
#endif

#if C_HAS_BUILTIN_EXPECT
#define GCC_UNLIKELY(x) __builtin_expect((x),0)
#define GCC_LIKELY(x) __builtin_expect((x),1)
#else
#define GCC_UNLIKELY(x) (x)
#define GCC_LIKELY(x) (x)
#endif

typedef         double     Real64;

#if SIZEOF_UNSIGNED_CHAR != 1
#  error "sizeof (unsigned char) != 1"
#else
  typedef unsigned char Bit8u;
  typedef   signed char Bit8s;
#endif

#if SIZEOF_UNSIGNED_SHORT != 2
#  error "sizeof (unsigned short) != 2"
#else
  typedef unsigned short Bit16u;
  typedef   signed short Bit16s;
#endif

#if SIZEOF_UNSIGNED_INT == 4
  typedef unsigned int Bit32u;
  typedef   signed int Bit32s;
#elif SIZEOF_UNSIGNED_LONG == 4
  typedef unsigned long Bit32u;
  typedef   signed long Bit32s;
#else
#  error "can't find sizeof(type) of 4 bytes!"
#endif

#if SIZEOF_UNSIGNED_LONG == 8
  typedef unsigned long Bit64u;
  typedef   signed long Bit64s;
#elif SIZEOF_UNSIGNED_LONG_LONG == 8
  typedef unsigned long long Bit64u;
  typedef   signed long long Bit64s;
#else
#  error "can't find data type of 8 bytes"
#endif

#if SIZEOF_INT_P == 4
  typedef Bit32u Bitu;
  typedef Bit32s Bits;
#else
  typedef Bit64u Bitu;
  typedef Bit64s Bits;
#endif
